import type { EndpointDef } from './types.js';
import { id, slug } from './types.js';

/**
 * All World of Warcraft Game Data API endpoint definitions.
 * Namespaces: static = static-{region}, dynamic = dynamic-{region}.
 */
export const gamedataEndpoints: EndpointDef[] = [
  // ── Achievement API ──────────────────────────────────
  {
    toolName: 'wow_achievement_index',
    title: 'Achievements Index',
    description: 'Returns an index of all achievements.',
    path: 'data/wow/achievement/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_achievement_get',
    title: 'Achievement',
    description: 'Returns an achievement by ID.',
    path: 'data/wow/achievement/{achievementId}',
    namespace: 'static',
    inputSchema: { achievementId: id('Achievement ID') },
  },
  {
    toolName: 'wow_achievement_media',
    title: 'Achievement Media',
    description: 'Returns media for an achievement by ID.',
    path: 'data/wow/media/achievement/{achievementId}',
    namespace: 'static',
    inputSchema: { achievementId: id('Achievement ID') },
  },
  {
    toolName: 'wow_achievementCategory_index',
    title: 'Achievement Categories Index',
    description: 'Returns an index of all achievement categories.',
    path: 'data/wow/achievement-category/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_achievementCategory_get',
    title: 'Achievement Category',
    description: 'Returns an achievement category by ID.',
    path: 'data/wow/achievement-category/{achievementCategoryId}',
    namespace: 'static',
    inputSchema: { achievementCategoryId: id('Achievement category ID') },
  },

  // ── Auction House API ────────────────────────────────
  {
    toolName: 'wow_auction_get',
    title: 'Auctions',
    description: 'Returns all active auctions for a connected realm.',
    path: 'data/wow/connected-realm/{connectedRealmId}/auctions',
    namespace: 'dynamic',
    inputSchema: { connectedRealmId: id('Connected realm ID') },
  },
  {
    toolName: 'wow_auction_commodities',
    title: 'Commodities',
    description: 'Returns all active commodity auctions (region-wide).',
    path: 'data/wow/auctions/commodities',
    namespace: 'dynamic',
    inputSchema: {},
  },

  // ── Azerite Essence API ──────────────────────────────
  {
    toolName: 'wow_azeriteEssence_index',
    title: 'Azerite Essences Index',
    description: 'Returns an index of all azerite essences.',
    path: 'data/wow/azerite-essence/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_azeriteEssence_get',
    title: 'Azerite Essence',
    description: 'Returns an azerite essence by ID.',
    path: 'data/wow/azerite-essence/{azeriteEssenceId}',
    namespace: 'static',
    inputSchema: { azeriteEssenceId: id('Azerite essence ID') },
  },
  {
    toolName: 'wow_azeriteEssence_search',
    title: 'Azerite Essence Search',
    description: 'Performs a search of azerite essences.',
    path: 'data/wow/search/azerite-essence',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_azeriteEssence_media',
    title: 'Azerite Essence Media',
    description: 'Returns media for an azerite essence by ID.',
    path: 'data/wow/media/azerite-essence/{azeriteEssenceId}',
    namespace: 'static',
    inputSchema: { azeriteEssenceId: id('Azerite essence ID') },
  },

  // ── Connected Realm API ──────────────────────────────
  {
    toolName: 'wow_connectedRealm_index',
    title: 'Connected Realms Index',
    description: 'Returns an index of connected realms.',
    path: 'data/wow/connected-realm/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_connectedRealm_get',
    title: 'Connected Realm',
    description: 'Returns a connected realm by ID.',
    path: 'data/wow/connected-realm/{connectedRealmId}',
    namespace: 'dynamic',
    inputSchema: { connectedRealmId: id('Connected realm ID') },
  },
  {
    toolName: 'wow_connectedRealm_search',
    title: 'Connected Realm Search',
    description: 'Performs a search of connected realms.',
    path: 'data/wow/search/connected-realm',
    namespace: 'dynamic',
    inputSchema: {},
    isSearch: true,
  },

  // ── Covenant API ─────────────────────────────────────
  {
    toolName: 'wow_covenant_index',
    title: 'Covenants Index',
    description: 'Returns an index of covenants.',
    path: 'data/wow/covenant/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_covenant_get',
    title: 'Covenant',
    description: 'Returns a covenant by ID.',
    path: 'data/wow/covenant/{covenantId}',
    namespace: 'static',
    inputSchema: { covenantId: id('Covenant ID') },
  },
  {
    toolName: 'wow_covenant_media',
    title: 'Covenant Media',
    description: 'Returns media for a covenant by ID.',
    path: 'data/wow/media/covenant/{covenantId}',
    namespace: 'static',
    inputSchema: { covenantId: id('Covenant ID') },
  },
  {
    toolName: 'wow_soulbind_index',
    title: 'Soulbinds Index',
    description: 'Returns an index of soulbinds.',
    path: 'data/wow/covenant/soulbind/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_soulbind_get',
    title: 'Soulbind',
    description: 'Returns a soulbind by ID.',
    path: 'data/wow/covenant/soulbind/{soulbindId}',
    namespace: 'static',
    inputSchema: { soulbindId: id('Soulbind ID') },
  },
  {
    toolName: 'wow_conduit_index',
    title: 'Conduits Index',
    description: 'Returns an index of conduits.',
    path: 'data/wow/covenant/conduit/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_conduit_get',
    title: 'Conduit',
    description: 'Returns a conduit by ID.',
    path: 'data/wow/covenant/conduit/{conduitId}',
    namespace: 'static',
    inputSchema: { conduitId: id('Conduit ID') },
  },

  // ── Creature API ─────────────────────────────────────
  {
    toolName: 'wow_creature_get',
    title: 'Creature',
    description: 'Returns a creature by ID.',
    path: 'data/wow/creature/{creatureId}',
    namespace: 'static',
    inputSchema: { creatureId: id('Creature ID') },
  },
  {
    toolName: 'wow_creature_search',
    title: 'Creature Search',
    description: 'Performs a search of creatures.',
    path: 'data/wow/search/creature',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_creature_displayMedia',
    title: 'Creature Display Media',
    description: 'Returns media for a creature display by ID.',
    path: 'data/wow/media/creature-display/{creatureDisplayId}',
    namespace: 'static',
    inputSchema: { creatureDisplayId: id('Creature display ID') },
  },
  {
    toolName: 'wow_creatureFamily_index',
    title: 'Creature Families Index',
    description: 'Returns an index of creature families.',
    path: 'data/wow/creature-family/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_creatureFamily_get',
    title: 'Creature Family',
    description: 'Returns a creature family by ID.',
    path: 'data/wow/creature-family/{creatureFamilyId}',
    namespace: 'static',
    inputSchema: { creatureFamilyId: id('Creature family ID') },
  },
  {
    toolName: 'wow_creatureFamily_media',
    title: 'Creature Family Media',
    description: 'Returns media for a creature family by ID.',
    path: 'data/wow/media/creature-family/{creatureFamilyId}',
    namespace: 'static',
    inputSchema: { creatureFamilyId: id('Creature family ID') },
  },
  {
    toolName: 'wow_creatureType_index',
    title: 'Creature Types Index',
    description: 'Returns an index of creature types.',
    path: 'data/wow/creature-type/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_creatureType_get',
    title: 'Creature Type',
    description: 'Returns a creature type by ID.',
    path: 'data/wow/creature-type/{creatureTypeId}',
    namespace: 'static',
    inputSchema: { creatureTypeId: id('Creature type ID') },
  },

  // ── Guild Crest API ──────────────────────────────────
  {
    toolName: 'wow_guildCrest_index',
    title: 'Guild Crest Components Index',
    description: 'Returns an index of guild crest media (borders and emblems).',
    path: 'data/wow/guild-crest/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_guildCrest_borderMedia',
    title: 'Guild Crest Border Media',
    description: 'Returns media for a guild crest border by ID.',
    path: 'data/wow/media/guild-crest/border/{borderId}',
    namespace: 'static',
    inputSchema: { borderId: id('Border ID') },
  },
  {
    toolName: 'wow_guildCrest_emblemMedia',
    title: 'Guild Crest Emblem Media',
    description: 'Returns media for a guild crest emblem by ID.',
    path: 'data/wow/media/guild-crest/emblem/{emblemId}',
    namespace: 'static',
    inputSchema: { emblemId: id('Emblem ID') },
  },

  // ── Heirloom API ─────────────────────────────────────
  {
    toolName: 'wow_heirloom_index',
    title: 'Heirlooms Index',
    description: 'Returns an index of heirlooms.',
    path: 'data/wow/heirloom/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_heirloom_get',
    title: 'Heirloom',
    description: 'Returns an heirloom by ID.',
    path: 'data/wow/heirloom/{heirloomId}',
    namespace: 'static',
    inputSchema: { heirloomId: id('Heirloom ID') },
  },

  // ── Housing Decor API ────────────────────────────────
  {
    toolName: 'wow_decor_index',
    title: 'Decor Index',
    description: 'Returns an index of housing decor.',
    path: 'data/wow/decor/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_decor_get',
    title: 'Decor',
    description: 'Returns a housing decor item by ID.',
    path: 'data/wow/decor/{decorId}',
    namespace: 'static',
    inputSchema: { decorId: id('Decor ID') },
  },
  {
    toolName: 'wow_decor_search',
    title: 'Decor Search',
    description: 'Performs a search of housing decor.',
    path: 'data/wow/search/decor',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_fixture_index',
    title: 'Fixture Index',
    description: 'Returns an index of housing fixtures.',
    path: 'data/wow/fixture/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_fixture_get',
    title: 'Fixture',
    description: 'Returns a housing fixture by ID.',
    path: 'data/wow/fixture/{fixtureId}',
    namespace: 'static',
    inputSchema: { fixtureId: id('Fixture ID') },
  },
  {
    toolName: 'wow_fixture_search',
    title: 'Fixture Search',
    description: 'Performs a search of housing fixtures.',
    path: 'data/wow/search/fixture',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_fixtureHook_index',
    title: 'Fixture Hook Index',
    description: 'Returns an index of fixture hooks.',
    path: 'data/wow/fixture-hook/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_fixtureHook_get',
    title: 'Fixture Hook',
    description: 'Returns a fixture hook by ID.',
    path: 'data/wow/fixture-hook/{fixtureHookId}',
    namespace: 'static',
    inputSchema: { fixtureHookId: id('Fixture hook ID') },
  },
  {
    toolName: 'wow_fixtureHook_search',
    title: 'Fixture Hook Search',
    description: 'Performs a search of fixture hooks.',
    path: 'data/wow/search/fixture-hook',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_room_index',
    title: 'Room Index',
    description: 'Returns an index of housing rooms.',
    path: 'data/wow/room/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_room_get',
    title: 'Room',
    description: 'Returns a housing room by ID.',
    path: 'data/wow/room/{roomId}',
    namespace: 'static',
    inputSchema: { roomId: id('Room ID') },
  },
  {
    toolName: 'wow_room_search',
    title: 'Room Search',
    description: 'Performs a search of housing rooms.',
    path: 'data/wow/search/room',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },

  // ── Item API ─────────────────────────────────────────
  {
    toolName: 'wow_item_get',
    title: 'Item',
    description: 'Returns an item by ID.',
    path: 'data/wow/item/{itemId}',
    namespace: 'static',
    inputSchema: { itemId: id('Item ID') },
  },
  {
    toolName: 'wow_item_search',
    title: 'Item Search',
    description: 'Performs a search of items.',
    path: 'data/wow/search/item',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_item_media',
    title: 'Item Media',
    description: 'Returns media for an item by ID.',
    path: 'data/wow/media/item/{itemId}',
    namespace: 'static',
    inputSchema: { itemId: id('Item ID') },
  },
  {
    toolName: 'wow_itemClass_index',
    title: 'Item Classes Index',
    description: 'Returns an index of item classes.',
    path: 'data/wow/item-class/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_itemClass_get',
    title: 'Item Class',
    description: 'Returns an item class by ID.',
    path: 'data/wow/item-class/{itemClassId}',
    namespace: 'static',
    inputSchema: { itemClassId: id('Item class ID') },
  },
  {
    toolName: 'wow_itemSet_index',
    title: 'Item Sets Index',
    description: 'Returns an index of item sets.',
    path: 'data/wow/item-set/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_itemSet_get',
    title: 'Item Set',
    description: 'Returns an item set by ID.',
    path: 'data/wow/item-set/{itemSetId}',
    namespace: 'static',
    inputSchema: { itemSetId: id('Item set ID') },
  },
  {
    toolName: 'wow_itemSubclass_get',
    title: 'Item Subclass',
    description: 'Returns an item subclass by class ID and subclass ID.',
    path: 'data/wow/item-class/{itemClassId}/item-subclass/{itemSubclassId}',
    namespace: 'static',
    inputSchema: {
      itemClassId: id('Item class ID'),
      itemSubclassId: id('Item subclass ID'),
    },
  },

  // ── Item Appearance API ──────────────────────────────
  {
    toolName: 'wow_itemAppearance_get',
    title: 'Item Appearance',
    description: 'Returns an item appearance by ID.',
    path: 'data/wow/item-appearance/{appearanceId}',
    namespace: 'static',
    inputSchema: { appearanceId: id('Appearance ID') },
  },
  {
    toolName: 'wow_itemAppearance_search',
    title: 'Item Appearance Search',
    description: 'Performs a search of item appearances.',
    path: 'data/wow/search/item-appearance',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_itemAppearanceSet_index',
    title: 'Item Appearance Sets Index',
    description: 'Returns an index of item appearance sets.',
    path: 'data/wow/item-appearance/set/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_itemAppearanceSet_get',
    title: 'Item Appearance Set',
    description: 'Returns an item appearance set by ID.',
    path: 'data/wow/item-appearance/set/{appearanceSetId}',
    namespace: 'static',
    inputSchema: { appearanceSetId: id('Appearance set ID') },
  },
  {
    toolName: 'wow_itemAppearanceSlot_index',
    title: 'Item Appearance Slot Index',
    description: 'Returns an index of item appearance slots.',
    path: 'data/wow/item-appearance/slot/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_itemAppearanceSlot_get',
    title: 'Item Appearance Slot',
    description: 'Returns an item appearance slot by slot type.',
    path: 'data/wow/item-appearance/slot/{slotType}',
    namespace: 'static',
    inputSchema: { slotType: slug('Slot type (e.g. "HEAD", "CHEST")') },
  },

  // ── Journal API ──────────────────────────────────────
  {
    toolName: 'wow_journalExpansion_index',
    title: 'Journal Expansions Index',
    description: 'Returns an index of journal expansions.',
    path: 'data/wow/journal-expansion/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_journalExpansion_get',
    title: 'Journal Expansion',
    description: 'Returns a journal expansion by ID.',
    path: 'data/wow/journal-expansion/{journalExpansionId}',
    namespace: 'static',
    inputSchema: { journalExpansionId: id('Journal expansion ID') },
  },
  {
    toolName: 'wow_journalEncounter_index',
    title: 'Journal Encounters Index',
    description: 'Returns an index of journal encounters.',
    path: 'data/wow/journal-encounter/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_journalEncounter_get',
    title: 'Journal Encounter',
    description: 'Returns a journal encounter by ID.',
    path: 'data/wow/journal-encounter/{journalEncounterId}',
    namespace: 'static',
    inputSchema: { journalEncounterId: id('Journal encounter ID') },
  },
  {
    toolName: 'wow_journalEncounter_search',
    title: 'Journal Encounter Search',
    description: 'Performs a search of journal encounters.',
    path: 'data/wow/search/journal-encounter',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },
  {
    toolName: 'wow_journalInstance_index',
    title: 'Journal Instances Index',
    description: 'Returns an index of journal instances (dungeons and raids).',
    path: 'data/wow/journal-instance/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_journalInstance_get',
    title: 'Journal Instance',
    description: 'Returns a journal instance by ID.',
    path: 'data/wow/journal-instance/{journalInstanceId}',
    namespace: 'static',
    inputSchema: { journalInstanceId: id('Journal instance ID') },
  },
  {
    toolName: 'wow_journalInstance_media',
    title: 'Journal Instance Media',
    description: 'Returns media for a journal instance by ID.',
    path: 'data/wow/media/journal-instance/{journalInstanceId}',
    namespace: 'static',
    inputSchema: { journalInstanceId: id('Journal instance ID') },
  },

  // ── Media Search API ─────────────────────────────────
  {
    toolName: 'wow_media_search',
    title: 'Media Search',
    description: 'Performs a search of all media assets.',
    path: 'data/wow/search/media',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },

  // ── Modified Crafting API ────────────────────────────
  {
    toolName: 'wow_modifiedCrafting_index',
    title: 'Modified Crafting Index',
    description: 'Returns the parent index of modified crafting.',
    path: 'data/wow/modified-crafting/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_modifiedCraftingCategory_index',
    title: 'Modified Crafting Category Index',
    description: 'Returns an index of modified crafting categories.',
    path: 'data/wow/modified-crafting/category/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_modifiedCraftingCategory_get',
    title: 'Modified Crafting Category',
    description: 'Returns a modified crafting category by ID.',
    path: 'data/wow/modified-crafting/category/{categoryId}',
    namespace: 'static',
    inputSchema: { categoryId: id('Modified crafting category ID') },
  },
  {
    toolName: 'wow_modifiedCraftingReagentSlotType_index',
    title: 'Modified Crafting Reagent Slot Type Index',
    description: 'Returns an index of modified crafting reagent slot types.',
    path: 'data/wow/modified-crafting/reagent-slot-type/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_modifiedCraftingReagentSlotType_get',
    title: 'Modified Crafting Reagent Slot Type',
    description: 'Returns a modified crafting reagent slot type by ID.',
    path: 'data/wow/modified-crafting/reagent-slot-type/{slotTypeId}',
    namespace: 'static',
    inputSchema: { slotTypeId: id('Reagent slot type ID') },
  },

  // ── Mount API ────────────────────────────────────────
  {
    toolName: 'wow_mount_index',
    title: 'Mounts Index',
    description: 'Returns an index of mounts.',
    path: 'data/wow/mount/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_mount_get',
    title: 'Mount',
    description: 'Returns a mount by ID.',
    path: 'data/wow/mount/{mountId}',
    namespace: 'static',
    inputSchema: { mountId: id('Mount ID') },
  },
  {
    toolName: 'wow_mount_search',
    title: 'Mount Search',
    description: 'Performs a search of mounts.',
    path: 'data/wow/search/mount',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },

  // ── Mythic Keystone Affix API ────────────────────────
  {
    toolName: 'wow_keystoneAffix_index',
    title: 'Mythic Keystone Affixes Index',
    description: 'Returns an index of mythic keystone affixes.',
    path: 'data/wow/keystone-affix/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_keystoneAffix_get',
    title: 'Mythic Keystone Affix',
    description: 'Returns a mythic keystone affix by ID.',
    path: 'data/wow/keystone-affix/{keystoneAffixId}',
    namespace: 'static',
    inputSchema: { keystoneAffixId: id('Keystone affix ID') },
  },
  {
    toolName: 'wow_keystoneAffix_media',
    title: 'Mythic Keystone Affix Media',
    description: 'Returns media for a mythic keystone affix by ID.',
    path: 'data/wow/media/keystone-affix/{keystoneAffixId}',
    namespace: 'static',
    inputSchema: { keystoneAffixId: id('Keystone affix ID') },
  },

  // ── Mythic Keystone Dungeon API ──────────────────────
  {
    toolName: 'wow_mythicKeystone_index',
    title: 'Mythic Keystone Index',
    description: 'Returns the parent index for mythic keystone resources.',
    path: 'data/wow/mythic-keystone/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_mythicKeystoneDungeon_index',
    title: 'Mythic Keystone Dungeons Index',
    description: 'Returns an index of mythic keystone dungeons.',
    path: 'data/wow/mythic-keystone/dungeon/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_mythicKeystoneDungeon_get',
    title: 'Mythic Keystone Dungeon',
    description: 'Returns a mythic keystone dungeon by ID.',
    path: 'data/wow/mythic-keystone/dungeon/{dungeonId}',
    namespace: 'dynamic',
    inputSchema: { dungeonId: id('Dungeon ID') },
  },
  {
    toolName: 'wow_mythicKeystonePeriod_index',
    title: 'Mythic Keystone Periods Index',
    description: 'Returns an index of mythic keystone periods.',
    path: 'data/wow/mythic-keystone/period/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_mythicKeystonePeriod_get',
    title: 'Mythic Keystone Period',
    description: 'Returns a mythic keystone period by ID.',
    path: 'data/wow/mythic-keystone/period/{periodId}',
    namespace: 'dynamic',
    inputSchema: { periodId: id('Period ID') },
  },
  {
    toolName: 'wow_mythicKeystoneSeason_index',
    title: 'Mythic Keystone Seasons Index',
    description: 'Returns an index of mythic keystone seasons.',
    path: 'data/wow/mythic-keystone/season/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_mythicKeystoneSeason_get',
    title: 'Mythic Keystone Season',
    description: 'Returns a mythic keystone season by ID.',
    path: 'data/wow/mythic-keystone/season/{seasonId}',
    namespace: 'dynamic',
    inputSchema: { seasonId: id('Season ID') },
  },

  // ── Mythic Keystone Leaderboard API ──────────────────
  {
    toolName: 'wow_mythicKeystoneLeaderboard_index',
    title: 'Mythic Keystone Leaderboards Index',
    description: 'Returns an index of mythic keystone leaderboards for a connected realm.',
    path: 'data/wow/connected-realm/{connectedRealmId}/mythic-leaderboard/index',
    namespace: 'dynamic',
    inputSchema: { connectedRealmId: id('Connected realm ID') },
  },
  {
    toolName: 'wow_mythicKeystoneLeaderboard_get',
    title: 'Mythic Keystone Leaderboard',
    description: 'Returns a mythic keystone leaderboard for a connected realm, dungeon, and period.',
    path: 'data/wow/connected-realm/{connectedRealmId}/mythic-leaderboard/{dungeonId}/period/{period}',
    namespace: 'dynamic',
    inputSchema: {
      connectedRealmId: id('Connected realm ID'),
      dungeonId: id('Dungeon ID'),
      period: id('Period ID'),
    },
  },

  // ── Mythic Raid Leaderboard API ──────────────────────
  {
    toolName: 'wow_mythicRaidLeaderboard_get',
    title: 'Mythic Raid Leaderboard',
    description: 'Returns the mythic raid leaderboard for a given raid and faction.',
    path: 'data/wow/leaderboard/hall-of-fame/{raid}/{faction}',
    namespace: 'dynamic',
    inputSchema: {
      raid: slug('Raid slug (e.g. "nerubar-palace")'),
      faction: slug('Faction: "horde" or "alliance"'),
    },
  },

  // ── Neighborhood API ─────────────────────────────────
  {
    toolName: 'wow_neighborhoodMap_index',
    title: 'Neighborhood Map Index',
    description: 'Returns an index of neighborhood maps.',
    path: 'data/wow/neighborhood-map/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_neighborhoodMap_get',
    title: 'Neighborhood Map',
    description: 'Returns a neighborhood map by ID.',
    path: 'data/wow/neighborhood-map/{neighborhoodMapId}',
    namespace: 'static',
    inputSchema: { neighborhoodMapId: id('Neighborhood map ID') },
  },
  {
    toolName: 'wow_neighborhood_get',
    title: 'Neighborhood',
    description: 'Returns a neighborhood within a neighborhood map.',
    path: 'data/wow/neighborhood-map/{neighborhoodMapId}/neighborhood/{neighborhoodId}',
    namespace: 'static',
    inputSchema: {
      neighborhoodMapId: id('Neighborhood map ID'),
      neighborhoodId: id('Neighborhood ID'),
    },
  },

  // ── Pet API ──────────────────────────────────────────
  {
    toolName: 'wow_pet_index',
    title: 'Pets Index',
    description: 'Returns an index of battle pets.',
    path: 'data/wow/pet/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_pet_get',
    title: 'Pet',
    description: 'Returns a battle pet by ID.',
    path: 'data/wow/pet/{petId}',
    namespace: 'static',
    inputSchema: { petId: id('Pet ID') },
  },
  {
    toolName: 'wow_pet_media',
    title: 'Pet Media',
    description: 'Returns media for a battle pet by ID.',
    path: 'data/wow/media/pet/{petId}',
    namespace: 'static',
    inputSchema: { petId: id('Pet ID') },
  },
  {
    toolName: 'wow_petAbility_index',
    title: 'Pet Abilities Index',
    description: 'Returns an index of pet abilities.',
    path: 'data/wow/pet-ability/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_petAbility_get',
    title: 'Pet Ability',
    description: 'Returns a pet ability by ID.',
    path: 'data/wow/pet-ability/{petAbilityId}',
    namespace: 'static',
    inputSchema: { petAbilityId: id('Pet ability ID') },
  },
  {
    toolName: 'wow_petAbility_media',
    title: 'Pet Ability Media',
    description: 'Returns media for a pet ability by ID.',
    path: 'data/wow/media/pet-ability/{petAbilityId}',
    namespace: 'static',
    inputSchema: { petAbilityId: id('Pet ability ID') },
  },

  // ── Playable Class API ───────────────────────────────
  {
    toolName: 'wow_playableClass_index',
    title: 'Playable Classes Index',
    description: 'Returns an index of playable classes.',
    path: 'data/wow/playable-class/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_playableClass_get',
    title: 'Playable Class',
    description: 'Returns a playable class by ID.',
    path: 'data/wow/playable-class/{classId}',
    namespace: 'static',
    inputSchema: { classId: id('Playable class ID') },
  },
  {
    toolName: 'wow_playableClass_media',
    title: 'Playable Class Media',
    description: 'Returns media for a playable class by ID.',
    path: 'data/wow/media/playable-class/{playableClassId}',
    namespace: 'static',
    inputSchema: { playableClassId: id('Playable class ID') },
  },
  {
    toolName: 'wow_playableClass_pvpTalentSlots',
    title: 'PvP Talent Slots',
    description: 'Returns the PvP talent slots for a playable class by ID.',
    path: 'data/wow/playable-class/{classId}/pvp-talent-slots',
    namespace: 'static',
    inputSchema: { classId: id('Playable class ID') },
  },

  // ── Playable Race API ────────────────────────────────
  {
    toolName: 'wow_playableRace_index',
    title: 'Playable Races Index',
    description: 'Returns an index of playable races.',
    path: 'data/wow/playable-race/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_playableRace_get',
    title: 'Playable Race',
    description: 'Returns a playable race by ID.',
    path: 'data/wow/playable-race/{playableRaceId}',
    namespace: 'static',
    inputSchema: { playableRaceId: id('Playable race ID') },
  },

  // ── Playable Specialization API ──────────────────────
  {
    toolName: 'wow_playableSpec_index',
    title: 'Playable Specializations Index',
    description: 'Returns an index of playable specializations.',
    path: 'data/wow/playable-specialization/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_playableSpec_get',
    title: 'Playable Specialization',
    description: 'Returns a playable specialization by ID.',
    path: 'data/wow/playable-specialization/{specId}',
    namespace: 'static',
    inputSchema: { specId: id('Specialization ID') },
  },
  {
    toolName: 'wow_playableSpec_media',
    title: 'Playable Specialization Media',
    description: 'Returns media for a playable specialization by ID.',
    path: 'data/wow/media/playable-specialization/{specId}',
    namespace: 'static',
    inputSchema: { specId: id('Specialization ID') },
  },

  // ── Power Type API ───────────────────────────────────
  {
    toolName: 'wow_powerType_index',
    title: 'Power Types Index',
    description: 'Returns an index of power types (mana, rage, energy, etc.).',
    path: 'data/wow/power-type/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_powerType_get',
    title: 'Power Type',
    description: 'Returns a power type by ID.',
    path: 'data/wow/power-type/{powerTypeId}',
    namespace: 'static',
    inputSchema: { powerTypeId: id('Power type ID') },
  },

  // ── Profession API ───────────────────────────────────
  {
    toolName: 'wow_profession_index',
    title: 'Professions Index',
    description: 'Returns an index of professions.',
    path: 'data/wow/profession/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_profession_get',
    title: 'Profession',
    description: 'Returns a profession by ID.',
    path: 'data/wow/profession/{professionId}',
    namespace: 'static',
    inputSchema: { professionId: id('Profession ID') },
  },
  {
    toolName: 'wow_profession_media',
    title: 'Profession Media',
    description: 'Returns media for a profession by ID.',
    path: 'data/wow/media/profession/{professionId}',
    namespace: 'static',
    inputSchema: { professionId: id('Profession ID') },
  },
  {
    toolName: 'wow_profession_skillTier',
    title: 'Profession Skill Tier',
    description: 'Returns a skill tier for a profession.',
    path: 'data/wow/profession/{professionId}/skill-tier/{skillTierId}',
    namespace: 'static',
    inputSchema: {
      professionId: id('Profession ID'),
      skillTierId: id('Skill tier ID'),
    },
  },
  {
    toolName: 'wow_recipe_get',
    title: 'Recipe',
    description: 'Returns a recipe by ID.',
    path: 'data/wow/recipe/{recipeId}',
    namespace: 'static',
    inputSchema: { recipeId: id('Recipe ID') },
  },
  {
    toolName: 'wow_recipe_media',
    title: 'Recipe Media',
    description: 'Returns media for a recipe by ID.',
    path: 'data/wow/media/recipe/{recipeId}',
    namespace: 'static',
    inputSchema: { recipeId: id('Recipe ID') },
  },

  // ── PvP Season API ───────────────────────────────────
  {
    toolName: 'wow_pvpSeason_index',
    title: 'PvP Seasons Index',
    description: 'Returns an index of PvP seasons.',
    path: 'data/wow/pvp-season/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_pvpSeason_get',
    title: 'PvP Season',
    description: 'Returns a PvP season by ID.',
    path: 'data/wow/pvp-season/{pvpSeasonId}',
    namespace: 'dynamic',
    inputSchema: { pvpSeasonId: id('PvP season ID') },
  },
  {
    toolName: 'wow_pvpLeaderboard_index',
    title: 'PvP Leaderboards Index',
    description: 'Returns an index of PvP leaderboards for a season.',
    path: 'data/wow/pvp-season/{pvpSeasonId}/pvp-leaderboard/index',
    namespace: 'dynamic',
    inputSchema: { pvpSeasonId: id('PvP season ID') },
  },
  {
    toolName: 'wow_pvpLeaderboard_get',
    title: 'PvP Leaderboard',
    description: 'Returns a PvP leaderboard for a season and bracket.',
    path: 'data/wow/pvp-season/{pvpSeasonId}/pvp-leaderboard/{pvpBracket}',
    namespace: 'dynamic',
    inputSchema: {
      pvpSeasonId: id('PvP season ID'),
      pvpBracket: slug('PvP bracket (e.g. "2v2", "3v3", "rbg")'),
    },
  },
  {
    toolName: 'wow_pvpReward_index',
    title: 'PvP Rewards Index',
    description: 'Returns an index of PvP rewards for a season.',
    path: 'data/wow/pvp-season/{pvpSeasonId}/pvp-reward/index',
    namespace: 'dynamic',
    inputSchema: { pvpSeasonId: id('PvP season ID') },
  },

  // ── PvP Tier API ─────────────────────────────────────
  {
    toolName: 'wow_pvpTier_index',
    title: 'PvP Tiers Index',
    description: 'Returns an index of PvP tiers.',
    path: 'data/wow/pvp-tier/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_pvpTier_get',
    title: 'PvP Tier',
    description: 'Returns a PvP tier by ID.',
    path: 'data/wow/pvp-tier/{pvpTierId}',
    namespace: 'static',
    inputSchema: { pvpTierId: id('PvP tier ID') },
  },
  {
    toolName: 'wow_pvpTier_media',
    title: 'PvP Tier Media',
    description: 'Returns media for a PvP tier by ID.',
    path: 'data/wow/media/pvp-tier/{pvpTierId}',
    namespace: 'static',
    inputSchema: { pvpTierId: id('PvP tier ID') },
  },

  // ── Quest API ────────────────────────────────────────
  {
    toolName: 'wow_quest_index',
    title: 'Quests Index',
    description: 'Returns an index of quests.',
    path: 'data/wow/quest/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_quest_get',
    title: 'Quest',
    description: 'Returns a quest by ID.',
    path: 'data/wow/quest/{questId}',
    namespace: 'static',
    inputSchema: { questId: id('Quest ID') },
  },
  {
    toolName: 'wow_questCategory_index',
    title: 'Quest Categories Index',
    description: 'Returns an index of quest categories.',
    path: 'data/wow/quest/category/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_questCategory_get',
    title: 'Quest Category',
    description: 'Returns a quest category by ID.',
    path: 'data/wow/quest/category/{questCategoryId}',
    namespace: 'static',
    inputSchema: { questCategoryId: id('Quest category ID') },
  },
  {
    toolName: 'wow_questArea_index',
    title: 'Quest Areas Index',
    description: 'Returns an index of quest areas.',
    path: 'data/wow/quest/area/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_questArea_get',
    title: 'Quest Area',
    description: 'Returns a quest area by ID.',
    path: 'data/wow/quest/area/{questAreaId}',
    namespace: 'static',
    inputSchema: { questAreaId: id('Quest area ID') },
  },
  {
    toolName: 'wow_questType_index',
    title: 'Quest Types Index',
    description: 'Returns an index of quest types.',
    path: 'data/wow/quest/type/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_questType_get',
    title: 'Quest Type',
    description: 'Returns a quest type by ID.',
    path: 'data/wow/quest/type/{questTypeId}',
    namespace: 'static',
    inputSchema: { questTypeId: id('Quest type ID') },
  },

  // ── Realm API ────────────────────────────────────────
  {
    toolName: 'wow_realm_index',
    title: 'Realms Index',
    description: 'Returns an index of realms.',
    path: 'data/wow/realm/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_realm_get',
    title: 'Realm',
    description: 'Returns a realm by slug.',
    path: 'data/wow/realm/{realmSlug}',
    namespace: 'dynamic',
    inputSchema: { realmSlug: slug('Realm slug (e.g. "tichondrius")') },
  },
  {
    toolName: 'wow_realm_search',
    title: 'Realm Search',
    description: 'Performs a search of realms.',
    path: 'data/wow/search/realm',
    namespace: 'dynamic',
    inputSchema: {},
    isSearch: true,
  },

  // ── Region API ───────────────────────────────────────
  {
    toolName: 'wow_region_index',
    title: 'Regions Index',
    description: 'Returns an index of regions.',
    path: 'data/wow/region/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
  {
    toolName: 'wow_region_get',
    title: 'Region',
    description: 'Returns a region by ID.',
    path: 'data/wow/region/{regionId}',
    namespace: 'dynamic',
    inputSchema: { regionId: id('Region ID') },
  },

  // ── Reputations API ──────────────────────────────────
  {
    toolName: 'wow_reputationFaction_index',
    title: 'Reputation Factions Index',
    description: 'Returns an index of reputation factions.',
    path: 'data/wow/reputation-faction/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_reputationFaction_get',
    title: 'Reputation Faction',
    description: 'Returns a reputation faction by ID.',
    path: 'data/wow/reputation-faction/{reputationFactionId}',
    namespace: 'static',
    inputSchema: { reputationFactionId: id('Reputation faction ID') },
  },
  {
    toolName: 'wow_reputationTiers_index',
    title: 'Reputation Tiers Index',
    description: 'Returns an index of reputation tiers.',
    path: 'data/wow/reputation-tiers/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_reputationTiers_get',
    title: 'Reputation Tiers',
    description: 'Returns a set of reputation tiers by ID.',
    path: 'data/wow/reputation-tiers/{reputationTiersId}',
    namespace: 'static',
    inputSchema: { reputationTiersId: id('Reputation tiers ID') },
  },

  // ── Spell API ────────────────────────────────────────
  {
    toolName: 'wow_spell_get',
    title: 'Spell',
    description: 'Returns a spell by ID.',
    path: 'data/wow/spell/{spellId}',
    namespace: 'static',
    inputSchema: { spellId: id('Spell ID') },
  },
  {
    toolName: 'wow_spell_media',
    title: 'Spell Media',
    description: 'Returns media for a spell by ID.',
    path: 'data/wow/media/spell/{spellId}',
    namespace: 'static',
    inputSchema: { spellId: id('Spell ID') },
  },
  {
    toolName: 'wow_spell_search',
    title: 'Spell Search',
    description: 'Performs a search of spells.',
    path: 'data/wow/search/spell',
    namespace: 'static',
    inputSchema: {},
    isSearch: true,
  },

  // ── Talent API ───────────────────────────────────────
  {
    toolName: 'wow_talentTree_index',
    title: 'Talent Tree Index',
    description: 'Returns an index of talent trees.',
    path: 'data/wow/talent-tree/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_talentTree_get',
    title: 'Talent Tree',
    description: 'Returns a talent tree by ID and specialization ID.',
    path: 'data/wow/talent-tree/{talentTreeId}/playable-specialization/{specId}',
    namespace: 'static',
    inputSchema: {
      talentTreeId: id('Talent tree ID'),
      specId: id('Playable specialization ID'),
    },
  },
  {
    toolName: 'wow_talentTree_nodes',
    title: 'Talent Tree Nodes',
    description: 'Returns all nodes for a talent tree by ID.',
    path: 'data/wow/talent-tree/{talentTreeId}',
    namespace: 'static',
    inputSchema: { talentTreeId: id('Talent tree ID') },
  },
  {
    toolName: 'wow_talent_index',
    title: 'Talents Index',
    description: 'Returns an index of talents.',
    path: 'data/wow/talent/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_talent_get',
    title: 'Talent',
    description: 'Returns a talent by ID.',
    path: 'data/wow/talent/{talentId}',
    namespace: 'static',
    inputSchema: { talentId: id('Talent ID') },
  },
  {
    toolName: 'wow_pvpTalent_index',
    title: 'PvP Talents Index',
    description: 'Returns an index of PvP talents.',
    path: 'data/wow/pvp-talent/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_pvpTalent_get',
    title: 'PvP Talent',
    description: 'Returns a PvP talent by ID.',
    path: 'data/wow/pvp-talent/{pvpTalentId}',
    namespace: 'static',
    inputSchema: { pvpTalentId: id('PvP talent ID') },
  },

  // ── Tech Talent API ──────────────────────────────────
  {
    toolName: 'wow_techTalentTree_index',
    title: 'Tech Talent Tree Index',
    description: 'Returns an index of tech talent trees.',
    path: 'data/wow/tech-talent-tree/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_techTalentTree_get',
    title: 'Tech Talent Tree',
    description: 'Returns a tech talent tree by ID.',
    path: 'data/wow/tech-talent-tree/{techTalentTreeId}',
    namespace: 'static',
    inputSchema: { techTalentTreeId: id('Tech talent tree ID') },
  },
  {
    toolName: 'wow_techTalent_index',
    title: 'Tech Talents Index',
    description: 'Returns an index of tech talents.',
    path: 'data/wow/tech-talent/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_techTalent_get',
    title: 'Tech Talent',
    description: 'Returns a tech talent by ID.',
    path: 'data/wow/tech-talent/{techTalentId}',
    namespace: 'static',
    inputSchema: { techTalentId: id('Tech talent ID') },
  },
  {
    toolName: 'wow_techTalent_media',
    title: 'Tech Talent Media',
    description: 'Returns media for a tech talent by ID.',
    path: 'data/wow/media/tech-talent/{techTalentId}',
    namespace: 'static',
    inputSchema: { techTalentId: id('Tech talent ID') },
  },

  // ── Title API ────────────────────────────────────────
  {
    toolName: 'wow_title_index',
    title: 'Titles Index',
    description: 'Returns an index of titles.',
    path: 'data/wow/title/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_title_get',
    title: 'Title',
    description: 'Returns a title by ID.',
    path: 'data/wow/title/{titleId}',
    namespace: 'static',
    inputSchema: { titleId: id('Title ID') },
  },

  // ── Toy API ──────────────────────────────────────────
  {
    toolName: 'wow_toy_index',
    title: 'Toys Index',
    description: 'Returns an index of toys.',
    path: 'data/wow/toy/index',
    namespace: 'static',
    inputSchema: {},
  },
  {
    toolName: 'wow_toy_get',
    title: 'Toy',
    description: 'Returns a toy by ID.',
    path: 'data/wow/toy/{toyId}',
    namespace: 'static',
    inputSchema: { toyId: id('Toy ID') },
  },

  // ── WoW Token API ────────────────────────────────────
  {
    toolName: 'wow_token_index',
    title: 'WoW Token Index',
    description: 'Returns the current WoW Token price.',
    path: 'data/wow/token/index',
    namespace: 'dynamic',
    inputSchema: {},
  },
];
